mensagem = (msg) => alert(msg);
soma = (a,b) => a + b;
sub = (a,b) => a - b;
mult = (a,b) => a * b;
div = (a,b) => a / b;
raiz = X => Math.sqrt(X);
//mensagem(soma(10,soma(8,2)));
//mensagem(soma(2,div(2,2)));
//mensagem(soma(div(80,2),mult(5,3)));
//mensagem(soma(sub(8,5),sub(3,70)));
